In [1]:
from baseline import *
from data_utils import *

In [2]:
#Fetch the training data
train_data = makeTrainingData(
    train_csv='train.csv',
    decription_csv='product_descriptions.csv',
    attrib_csv='attributes.csv',
    merge_col='product_uid'
)
train_data.head(6)

,id,product_uid,product_title,search_term,relevance,brand,product_description
0,2,100001,Simpson Strong-Tie 12-Gauge Angle,angle bracket,3.00,Simpson Strong-Tie,"Not only do angles make joints stronger, they ..."
1,3,100001,Simpson Strong-Tie 12-Gauge Angle,l bracket,2.50,Simpson Strong-Tie,"Not only do angles make joints stronger, they ..."
2,9,100002,BEHR Premium Textured DeckOver 1-gal. #SC-141 ...,deck over,3.00,BEHR Premium Textured DeckOver,BEHR Premium Textured DECKOVER is an innovativ...
3,16,100005,Delta Vero 1-Handle Shower Only Faucet Trim Ki...,rain shower head,2.33,Delta,Update your bathroom with the Delta Vero Singl...
4,17,100005,Delta Vero 1-Handle Shower Only Faucet Trim Ki...,shower only faucet,2.67,Delta,Update your bathroom with the Delta Vero Singl...
5,18,100006,Whirlpool 1.9 cu. ft. Over the Range Convectio...,convection otr,3.00,Whirlpool,Achieving delicious results is almost effortle...

In [3]:
#Fill Na in the brand name
train_data['brand'].fillna('',inplace=True)

# basic spell correct search query
scb = SpellingCorrectionBaseline()

train_data['search_term'] = train_data['search_term'].apply(lambda x: scb.spellCorrectBaseline(x))
scb.dicAppender()

In [4]:
#Rank the prouducts based relavence
train_ranked = rankByRelevance(train_data)
train_ranked.head(5)

,id,product_uid,product_title,search_term,relevance,brand,product_description,rank
20059,61851,116711,GE Z-Wave 1800-Watt Resistive CFL-LED Indoor P...,zwave switch,3.00,,Transform any home into a smart home with the ...,1
40066,122225,141628,Leviton Z-Wave Controls 3-Way/Remote Scene Cap...,zwave switch,3.00,Leviton,The Leviton DZMX1 is a Z-Wave enabled universa...,2
40342,123081,142033,Leviton Decora Z-Wave Controls 15 Amp Scene Ca...,zwave switch,3.00,Leviton,The Leviton DZS15 is a Z-Wave enabled universa...,3
35763,109349,135547,GE Z-Wave 600 Watt CFL-LED Indoor In-Wall Dimm...,zwave switch,2.67,,Transform any home into a smart home with the ...,4
47359,143778,152640,Z-Wave Wireless Lighting Control with Keypad C...,zwave switch,2.67,,Transform any home into a smart home with the ...,5

In [5]:
#Cleaning the data and removing unnecessary columns
train_cleaned = cleanPandasDF(
    ranked_df=train_ranked,
    col_list_clean=['product_title','search_term','brand','product_description'],
    col_list_drop=['id']
)
train_cleaned.head(5)

cleanPandasDF: 100%|██████████| 4/4 [03:41<00:00, 55.31s/it]

,id,product_uid,product_title,search_term,relevance,brand,product_description,rank
20059,61851,116711,"(ge, z, wave, 1800, watt, resist, cfl, led, in...","(zwave, switch)",3.00,(),"(transform, ani, home, into, a, smart, home, w...",1
40066,122225,141628,"(leviton, z, wave, control, 3, way/remot, scen...","(zwave, switch)",3.00,"(leviton,)","(the, leviton, dzmx1, is, a, z, wave, enabl, u...",2
40342,123081,142033,"(leviton, decora, z, wave, control, 15, amp, s...","(zwave, switch)",3.00,"(leviton,)","(the, leviton, dzs15, is, a, z, wave, enabl, u...",3
35763,109349,135547,"(ge, z, wave, 600, watt, cfl, led, indoor, in,...","(zwave, switch)",2.67,(),"(transform, ani, home, into, a, smart, home, w...",4
47359,143778,152640,"(z, wave, wireless, light, control, with, keyp...","(zwave, switch)",2.67,(),"(transform, ani, home, into, a, smart, home, w...",5

In [6]:
train_cleaned['brand'] = train_cleaned['brand'].apply(lambda x: " ".join(list(x)))
train_cleaned['product_description'] = train_cleaned['product_description'].apply(lambda x: " ".join(list(x)))
train_cleaned['product_title'] = train_cleaned['product_title'].apply(lambda x: " ".join(list(x)))
train_cleaned['search_term'] = train_cleaned['search_term'].apply(lambda x: " ".join(list(x)))

In [7]:
train_cleaned

,id,product_uid,product_title,search_term,relevance,brand,product_description,rank
20059,61851,116711,ge z wave 1800 watt resist cfl led indoor plug...,zwave switch,3.00,,transform ani home into a smart home with the ...,1
40066,122225,141628,leviton z wave control 3 way/remot scene capab...,zwave switch,3.00,leviton,the leviton dzmx1 is a z wave enabl univers di...,2
40342,123081,142033,leviton decora z wave control 15 amp scene cap...,zwave switch,3.00,leviton,the leviton dzs15 is a z wave enabl univers sw...,3
35763,109349,135547,ge z wave 600 watt cfl led indoor in wall dimm...,zwave switch,2.67,,transform ani home into a smart home with the ...,4
47359,143778,152640,z wave wireless light control with keypad control,zwave switch,2.67,,transform ani home into a smart home with the ...,5
...,...,...,...,...,...,...,...,...
24556,75396,121588,pro seri 19 piec hole saw set with case,hole saw,2.33,pro seri,the pro seri 19 piec hole saw blade set contai...,4
27842,85412,125403,ryobi hole saw set 6 piec,hole saw,2.33,ryobi,these carbon steel hole saw from ryobi are per...,5
14985,46280,111472,bosch daredevil spade bit set 10 piec,hole saw,2.00,bosch,the bosch daredevil spade bit set of 10in. clu...,6
34082,104248,133315,milwauke 3/8in. ergo quick chang saw arbor,hole saw,2.00,milwauke,make hole saw bit chang quickli and easili wit...,7
70140,210176,197110,milwauke 2in. to 7in. dia. adjust hole cutter,hole saw,1.33,milwauke,the milwauke adjust hole cutter offer 1 size f...,8

In [3]:
train_cleaned.to_csv('train_dssm3.csv',header=True,index=False)

### TEST DATA

In [1]:
from baseline import *
from data_utils import *
test_data = pd.read_csv('data/test_new.csv',encoding='ISO-8859-1')

In [2]:
test_data = test_data.rename(columns={'query': 'search_term','_unit_id':'product_uid'})
test_data.head(4)

,Unnamed: 0,product_uid,relevance,relevance:variance,product_image,product_link,product_price,product_title,search_term,rank,source,url,product_description,brand
0,0,711158459,3.67,0.471,http://thumbs2.ebaystatic.com/d/l225/m/mzvzEUI...,http://www.ebay.com/itm/Sony-PlayStation-4-PS4...,$329.98,Sony PlayStation 4 (PS4) (Latest Model)- 500 G...,playstation 4,1,eBay,http://www.ebay.com/sch/i.html?_from=R40&_trks...,The PlayStation 4 system opens the door to an ...,Sony
1,1,711158460,4.00,0.000,http://thumbs3.ebaystatic.com/d/l225/m/mJNDmSy...,http://www.ebay.com/itm/Sony-PlayStation-4-Lat...,$324.84,Sony PlayStation 4 (Latest Model)- 500 GB Jet ...,playstation 4,2,eBay,http://www.ebay.com/sch/i.html?_from=R40&_trks...,The PlayStation 4 system opens the door to an ...,Sony
2,2,711158461,4.00,0.000,http://thumbs4.ebaystatic.com/d/l225/m/m10NZXA...,http://www.ebay.com/itm/Sony-PlayStation-4-PS4...,$324.83,Sony PlayStation 4 PS4 500 GB Jet Black Console,playstation 4,3,eBay,http://www.ebay.com/sch/i.html?_from=R40&_trks...,The PlayStation 4 system opens the door to an ...,Sony
3,3,711158462,3.67,0.471,http://thumbs2.ebaystatic.com/d/l225/m/mZZXTmA...,http://www.ebay.com/itm/Sony-PlayStation-4-500...,$350.00,Sony - PlayStation 4 500GB The Last of Us Rema...,playstation 4,4,eBay,http://www.ebay.com/sch/i.html?_from=R40&_trks...,NaN,Sony

In [3]:
test_data['brand'].fillna('',inplace=True)

# basic spell correct search query
scb = SpellingCorrectionBaseline()

test_data['search_term'] = test_data['search_term'].apply(lambda x: scb.spellingCheckNew(x))
scb.dicAppender()

In [4]:
# test_cleaned = test_data.dropna().reset_index().drop(['index'],axis=1)
test_cleaned = cleanPandasDF(
    ranked_df=test_data,
    col_list_clean=['product_title','search_term','brand','product_description'],
    col_list_drop=['url','url','product_price','product_link','product_image','relevance:variance','source']
)
test_cleaned = test_cleaned.loc[:, ~test_cleaned.columns.str.match('Unnamed')]
test_cleaned.head(5)

cleanPandasDF: 100%|██████████| 4/4 [00:33<00:00,  8.37s/it]

,product_uid,relevance,product_title,search_term,rank,product_description,brand
0,711158459,3.67,"(soni, playstat, 4, ps4, latest, model, 500, g...","(playstat, 4)",1,"(the, playstat, 4, system, open, the, door, to...","(soni,)"
1,711158460,4.00,"(soni, playstat, 4, latest, model, 500, gb, je...","(playstat, 4)",2,"(the, playstat, 4, system, open, the, door, to...","(soni,)"
2,711158461,4.00,"(soni, playstat, 4, ps4, 500, gb, jet, black, ...","(playstat, 4)",3,"(the, playstat, 4, system, open, the, door, to...","(soni,)"
3,711158462,3.67,"(soni, playstat, 4, 500gb, the, last, of, us, ...","(playstat, 4)",4,"(<UNK>,)","(soni,)"
4,711158463,3.33,"(soni, playstat, 4, ps4, latest, model, 500, g...","(playstat, 4)",5,"(the, playstat, 4, system, open, the, door, to...","(soni,)"

In [5]:
test_cleaned['brand'] = test_cleaned['brand'].apply(lambda x: " ".join(list(x)))
test_cleaned['product_description'] = test_cleaned['product_description'].apply(lambda x: " ".join(list(x)))
test_cleaned['product_title'] = test_cleaned['product_title'].apply(lambda x: " ".join(list(x)))
test_cleaned['search_term'] = test_cleaned['search_term'].apply(lambda x: " ".join(list(x)))

In [9]:
test_cleaned.to_csv('data/test_final.csv',header=True,index=False)